### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by Suleman-Elahi** [LGUG2Z/unsubscan#1]
![image](https://user-images.githubusercontent.com/24384996/174422918-4e875f91-d60e-4526-88b5-e109012bc336.png)

It won't even download with an exception. See if it can be fixed.

**Comment by LGUG2Z** [comment]
Unfortunately a known issue for us poor souls trying to publish compiled binaries for Windows users to distribute in zip files on GH releases. One of many examples here: https://github.com/liquidctl/liquidctl/issues/370

I am also a Windows user and long ago I had to spend a significant amount of time wrestling with Windows Defender to be able to do something as simple as download a zipped release from GitHub.

I can try reaching out to MS about this false positive, but I'm not going to hold my breath. For now your options are to either spend some time tweaking your Windows Defender settings or compiling from source.

Over the weekend I'll work on publishing this to `scoop` to provide an alternative avenue for installation of prebuilt binaries.

Apologies that I don't have better news for you. 😞

**Comment by LGUG2Z** [comment]
PR opened to scoop's `extras` bucket: https://github.com/ScoopInstaller/Extras/pull/8713

**Comment by LGUG2Z** [comment]
https://www.virustotal.com/gui/file/fb00e0c43336787eeb12151e35bbddf6f0190eded4431bfdcf7776fbda806fdf for additional peace of mind, no viruses detected. 😅

**Comment by LGUG2Z** [comment]
`unsubscan` can now be installed on Windows via `scoop` after adding the `extras` bucket. Steps have been documented on the readme.

**Comment by Suleman-Elahi** [comment]
Would it be possible to add it to `winget` as well? That's built into window now.
